const CategoriesSectionCardArray = [
  {
    title: "Mathematics",
    li1: "Arithmetic",
    li2: "Geometry",
    li3: "Trignometry",
    li4: "Calculus",
    li5: "Statistics",
    li6: "",
  },
  {
    title: "Science",
    li1: "Physics",
    li2: "Chemistry",
    li3: "Biology",
    li4: "Earth Science",
    li5: "Environmental Science",
    li6: "Astronomy",
  },
  {
    title: "Technology",
    li1: "Computer Science",
    li2: "Programming Languages",
    li3: "Web Development",
    li4: "Data Science",
    li5: "Cybersecurity",
    li6: "Artificial Intelligence",
  },
  {
    title: "Languages",
    li1: "English",
    li2: "Spanish",
    li3: "French",
    li4: "German",
    li5: "Mandarin",
    li6: "Japanese",
  },
  {
    title: "History",
    li1: "World History",
    li2: "Ancient Civilizations",
    li3: "Modern History",
    li4: "American History",
    li5: "European History",
    li6: "",
  },
  {
    title: "Arts",
    li1: "Music",
    li2: "Drawing & Painting",
    li3: "Photography",
    li4: "Film & Video",
    li5: "Theater",
    li6: "",
  },
  {
    title: "Literature",
    li1: "Classic Literature",
    li2: "Modern Fiction",
    li3: "Poetry",
    li4: "Literary Analysis",
    li5: "Writing & Composition",
    li6: "",
  },
  {
    title: "Business",
    li1: "Economics",
    li2: "Finance",
    li3: "Marketing",
    li4: "Entrepreneurship",
    li5: "Management",
    li6: "",
  },
  {
    title: "Social Sciences",
    li1: "Phycology",
    li2: "Sociology",
    li3: "Political Science",
    li4: "Anthropology",
    li5: "",
    li6: "",
  },
  {
    title: "Life Skills",
    li1: "Personal Finance",
    li2: "Time Management",
    li3: "Communication Skills",
    li4: "Leadership & Teamwork",
    li5: "",
    li6: "",
  },
  {
    title: "Test Preparation",
    li1: "SAT/ACT",
    li2: "GRE",
    li3: "TOEFL/IELTS",
    li4: "Professional Cerfications",
    li5: "",
    li6: "",
  },
  {
    title: "Engineering",
    li1: "Mechanical Engineering",
    li2: "Electrical Engineering  ",
    li3: "Civil Engineering",
    li4: "Chemical Enginnering",
    li5: "",
    li6: "",
  },
  {
    title: "Environmental Studies",
    li1: "Climate Change",
    li2: "Sustainable Living",
    li3: "Renewable Energy",
    li4: "",
    li5: "",
    li6: "",
  },
  {
    title: "Hobbies & Crafts",
    li1: "Cooking",
    li2: "Gardening",
    li3: "DIY Projects",
    li4: "Knitting & Sewing",
    li5: "",
    li6: "",
  },
 
];

export default CategoriesSectionCardArray;
